// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../../mocks/mock_service.go -package=mocks Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	service "github.com/maxon2034/trainee-go-cart-api/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockService) AddItem(ctx context.Context, cartId uuid.UUID, product string, price float64) (service.CartItemDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, cartId, product, price)
	ret0, _ := ret[0].(service.CartItemDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItem indicates an expected call of AddItem.
func (mr *MockServiceMockRecorder) AddItem(ctx, cartId, product, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockService)(nil).AddItem), ctx, cartId, product, price)
}

// CreateCart mocks base method.
func (m *MockService) CreateCart(ctx context.Context) (service.CartDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", ctx)
	ret0, _ := ret[0].(service.CartDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockServiceMockRecorder) CreateCart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockService)(nil).CreateCart), ctx)
}

// UpdateCartItem mocks base method.
func (m *MockService) UpdateCartItem(ctx context.Context, ID uuid.UUID, newProduct string, newPrice float64) (service.CartItemDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", ctx, ID, newProduct, newPrice)
	ret0, _ := ret[0].(service.CartItemDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockServiceMockRecorder) UpdateCartItem(ctx, ID, newProduct, newPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockService)(nil).UpdateCartItem), ctx, ID, newProduct, newPrice)
}

// ViewCart mocks base method.
func (m *MockService) ViewCart(ctx context.Context, id uuid.UUID) (service.CartDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewCart", ctx, id)
	ret0, _ := ret[0].(service.CartDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewCart indicates an expected call of ViewCart.
func (mr *MockServiceMockRecorder) ViewCart(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewCart", reflect.TypeOf((*MockService)(nil).ViewCart), ctx, id)
}
