// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../mocks/mock_repository.go -package=mocks Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/maxon2034/trainee-go-cart-api/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddCart mocks base method.
func (m *MockRepository) AddCart(ctx context.Context) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCart", ctx)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCart indicates an expected call of AddCart.
func (mr *MockRepositoryMockRecorder) AddCart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCart", reflect.TypeOf((*MockRepository)(nil).AddCart), ctx)
}

// AddCartItem mocks base method.
func (m *MockRepository) AddCartItem(ctx context.Context, cartId uuid.UUID, product string, price float64) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCartItem", ctx, cartId, product, price)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCartItem indicates an expected call of AddCartItem.
func (mr *MockRepositoryMockRecorder) AddCartItem(ctx, cartId, product, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCartItem", reflect.TypeOf((*MockRepository)(nil).AddCartItem), ctx, cartId, product, price)
}

// GetCart mocks base method.
func (m *MockRepository) GetCart(ctx context.Context, id uuid.UUID) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, id)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockRepositoryMockRecorder) GetCart(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockRepository)(nil).GetCart), ctx, id)
}

// RemoveCartItem mocks base method.
func (m *MockRepository) RemoveCartItem(ctx context.Context, itemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCartItem", ctx, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCartItem indicates an expected call of RemoveCartItem.
func (mr *MockRepositoryMockRecorder) RemoveCartItem(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCartItem", reflect.TypeOf((*MockRepository)(nil).RemoveCartItem), ctx, itemID)
}

// UpdateCartItem mocks base method.
func (m *MockRepository) UpdateCartItem(ctx context.Context, ID uuid.UUID, newProduct string, newPrice float64) (*entity.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", ctx, ID, newProduct, newPrice)
	ret0, _ := ret[0].(*entity.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockRepositoryMockRecorder) UpdateCartItem(ctx, ID, newProduct, newPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockRepository)(nil).UpdateCartItem), ctx, ID, newProduct, newPrice)
}
