// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../../mocks/mock_service.go -package=mocks Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/maxon2034/trainee-go-cart-api/internal/entity"
	service "github.com/maxon2034/trainee-go-cart-api/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockService) AddItem(ctx context.Context, cartID uuid.UUID, product string, price float64) (*service.CartItemDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, cartID, product, price)
	ret0, _ := ret[0].(*service.CartItemDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItem indicates an expected call of AddItem.
func (mr *MockServiceMockRecorder) AddItem(ctx, cartID, product, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockService)(nil).AddItem), ctx, cartID, product, price)
}

// CalculateDiscount mocks base method.
func (m *MockService) CalculateDiscount(ctx context.Context, cartID uuid.UUID) (*entity.CartDiscount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateDiscount", ctx, cartID)
	ret0, _ := ret[0].(*entity.CartDiscount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateDiscount indicates an expected call of CalculateDiscount.
func (mr *MockServiceMockRecorder) CalculateDiscount(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateDiscount", reflect.TypeOf((*MockService)(nil).CalculateDiscount), ctx, cartID)
}

// CreateCart mocks base method.
func (m *MockService) CreateCart(ctx context.Context) (*service.CartDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", ctx)
	ret0, _ := ret[0].(*service.CartDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockServiceMockRecorder) CreateCart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockService)(nil).CreateCart), ctx)
}

// RemoveItem mocks base method.
func (m *MockService) RemoveItem(ctx context.Context, cartID, itemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, cartID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockServiceMockRecorder) RemoveItem(ctx, cartID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockService)(nil).RemoveItem), ctx, cartID, itemID)
}

// UpdateCartItem mocks base method.
func (m *MockService) UpdateCartItem(ctx context.Context, cartID, itemID uuid.UUID, newProduct string, newPrice float64) (*service.CartItemDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", ctx, cartID, itemID, newProduct, newPrice)
	ret0, _ := ret[0].(*service.CartItemDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockServiceMockRecorder) UpdateCartItem(ctx, cartID, itemID, newProduct, newPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockService)(nil).UpdateCartItem), ctx, cartID, itemID, newProduct, newPrice)
}

// ViewCart mocks base method.
func (m *MockService) ViewCart(ctx context.Context, cartID uuid.UUID) (*service.CartDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewCart", ctx, cartID)
	ret0, _ := ret[0].(*service.CartDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewCart indicates an expected call of ViewCart.
func (mr *MockServiceMockRecorder) ViewCart(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewCart", reflect.TypeOf((*MockService)(nil).ViewCart), ctx, cartID)
}
